question_data = [
                  {"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.","correct_answer":"False","incorrect_answers":["True"]},
                  {"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"The Sun rises from the North.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"Vietnams national flag is a red star in front of a yellow background.","correct_answer":"False","incorrect_answers":["True"]},
                  {"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"The disease cancer in itself is not contagious.","correct_answer":"True","incorrect_answers":["False"]},
                  {"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"Bulls are attracted to the color red.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"The color orange is named after the fruit.","correct_answer":"True","incorrect_answers":["False"]},
                  {"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.","correct_answer":"False","incorrect_answers":["True"]},
                  {"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"All strawberries are red.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"French is an official language in Canada.","correct_answer":"True","incorrect_answers":["False"]},
                  {"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"The Great Wall of China is visible from the moon.","correct_answer":"False","incorrect_answers":["True"]}
                  ]
